	
	
	--CREATE TABLE [dbo].[MEMBER_LIST] WITH (
 --         DISTRIBUTION = HASH (MEMBER_KEY),
 --         CLUSTERED INDEX (MEMBER_KEY ASC) )
 --         AS
	SELECT DISTINCT TOP 100000 

	'{"member_key": '+CAST(C.MEMBER_KEY AS VARCHAR(20))+',' AS MEMBER_KEY,
	'"mm_count": '+ CAST(M.MM_COUNT AS VARCHAR(20))+',' AS MM_COUNT,
	'"amt_paid": '+ CAST(CAST(C.AMT_PAID AS DECIMAL(15,0)) AS VARCHAR(20))+',' AS AMT_PAID,
	'"amt_allowed": '+ CAST(CAST(C.AMT_ALLOWED AS DECIMAL(15,0)) AS VARCHAR(20))+',' AS AMT_ALLOWED,
	'"qty_ed_admits": '+ CAST(C.QTY_ED_ADMITS AS VARCHAR(20))+',' AS QTY_ED_ADMITS,
	'"qty_admits": '+CAST(CAST(C.ADMITS AS INT) AS VARCHAR(20))+',' AS QTY_ADMITS,
	'"qty_days": '+CAST(CAST(C.QTY_DAYS AS INT) AS VARCHAR(20))+',' AS QTY_DAYS,
	'"avg_los": '+CAST(CAST((CASE WHEN C.ADMITS = 0 THEN 0 ELSE C.QTY_DAYS/C.ADMITS END) AS DECIMAL(10,1)) AS VARCHAR(20))+','	AS AVG_LOS,

	--'"cur_pro_prim_condition": "'+CAST(MARA.CLINICAL_LABEL AS VARCHAR(80))+'",' AS CUR_PRO_PRIM_CONDITION,
	--'"cur_pro_prim_condition_group": "'+CAST(MARA_DIM.MARA_SUMMARY_GROUP_DESCRIPTION AS VARCHAR(80))+'",' AS CUR_PRO_PRIM_CONDITION_GROUP,

	'"cur_pros_risk_score": '+CAST(CAST(M.CUR_PROS_RISK_SCORE AS DECIMAL(10,2)) AS VARCHAR(20))+',' AS CUR_PROS_RISK_SCORE,
	'"cur_pro_rx": '+CAST(CAST(M.CUR_PRO_RX AS DECIMAL(10,2)) AS VARCHAR(20))+',' AS CUR_PRO_RX,
	'"cur_pro_ip": '+ CAST(CAST(M.CUR_PRO_IP AS DECIMAL(10,2))  AS VARCHAR(20))+',' AS CUR_PRO_IP,
	'"cur_pro_op": '+ CAST(CAST(M.CUR_PRO_OP AS DECIMAL(10,2)) AS VARCHAR(20))+',' AS CUR_PRO_OP,
	'"cur_pro_physician": '+ CAST(CAST(M.CUR_PRO_PHYSICIAN  AS DECIMAL(10,2)) AS VARCHAR(20))+',' AS CUR_PRO_PHYSICIAN,
	'"prev_pros_risk_score": '+ CAST(CAST(M.PREV_PROS_RISK_SCORE  AS DECIMAL(10,2)) AS VARCHAR(20))+',' AS PREV_PROS_RISK_SCORE,
	'"prev_pro_rx": '+ CAST(CAST(M.PREV_PRO_RX  AS DECIMAL(10,2)) AS VARCHAR(20))+',' AS PREV_PRO_RX,
	'"prev_pro_op": '+ CAST(CAST(M.PREV_PRO_OP AS DECIMAL(10,2)) AS VARCHAR(20))+',' AS PREV_PRO_OP,
	'"prev_pro_ip": '+ CAST(CAST(M.PREV_PRO_IP AS DECIMAL(10,2)) AS  VARCHAR(20))+',' AS PREV_PRO_IP,
	'"prev_pro_physician": '+ CAST(CAST(M.PREV_PRO_PHYSICIAN  AS DECIMAL(10,2)) AS VARCHAR(20))+'},' AS PREV_PRO_PHYSICIAN
	FROM 
	(SELECT
	S.MEMBER_KEY,
	SUM(S.AMT_PAID) AS AMT_PAID,
	SUM(S.AMT_ALLOWED) AS AMT_ALLOWED,
	SUM(COALESCE(S.QTY_ER_ADMITS, 0)) AS QTY_ED_ADMITS,
	SUM(CASE WHEN H.HCG_SETTING = 'HIP' THEN S.MI_CASES ELSE 0 END) AS ADMITS,
	SUM(CASE WHEN H.HCG_SETTING = 'HIP' THEN S.MI_UTILS ELSE 0 END) AS QTY_DAYS
	FROM FACT_SERVICES s 
	LEFT JOIN DIM_HCG H
		ON S.MR_LINE_CASE_KEY = H.MR_LINE_KEY
	WHERE S.MEMBER_KEY < 100000
	GROUP BY S.MEMBER_KEY) C

	JOIN

	(SELECT DISTINCT MM_A.MEMBER_KEY,
	SUM(MMC. MM) AS MM_COUNT,
	SUM(MM_A.PRO_RX + MM_A.PRO_IP + MM_A.PRO_OP + MM_A.PRO_PHYSICIAN) AS CUR_PROS_RISK_SCORE,
	SUM(MM_A.PRO_RX) AS CUR_PRO_RX,
	SUM(MM_A.PRO_IP) AS CUR_PRO_IP,
	SUM(MM_A.PRO_OP) AS CUR_PRO_OP,
	SUM(MM_A.PRO_PHYSICIAN) AS CUR_PRO_PHYSICIAN,
	SUM(MM_B.PRO_RX + MM_B.PRO_IP + MM_B.PRO_OP + MM_B.PRO_PHYSICIAN) AS PREV_PROS_RISK_SCORE,
	SUM(MM_B.PRO_RX) AS PREV_PRO_RX,
	SUM(MM_B.PRO_IP) AS PREV_PRO_IP,
	SUM(MM_B.PRO_OP) AS PREV_PRO_OP,
	SUM(MM_B.PRO_PHYSICIAN) AS PREV_PRO_PHYSICIAN
	FROM FACT_MEMBER_MONTH MM_A
	LEFT JOIN FACT_MEMBER_MONTH MM_B
	ON MM_A.MEMBER_KEY = MM_B.MEMBER_KEY
	LEFT JOIN DIM_MARA MARA
	ON MM_A.MARA_PRO_CONDITION_KEY = MARA.MARACLASS_KEY
	JOIN
		(SELECT 
		MM.MEMBER_KEY,
		SUM(MM.MM_UNITS) AS MM
		FROM FACT_MEMBER_MONTH MM
		GROUP BY MM.MEMBER_KEY) MMC
	ON MM_A.MEMBER_KEY = MMC.MEMBER_KEY
	WHERE MM_A.DATE_KEY = 20160101
	AND MM_B.DATE_KEY = 20150101
	AND MM_A.MM_UNITS = 1 AND MM_B.MM_UNITS = 1
	AND MM_A.MEMBER_KEY < 100000 AND MM_B.MEMBER_KEY < 100000
	GROUP BY MM_A.MEMBER_KEY
	) M

	ON C.MEMBER_KEY = M.MEMBER_KEY

	LEFT JOIN (
		
		SELECT
		B.MEMBER_KEY
		,B.CLINICAL_LABEL
		,DENSE_RANK() OVER (PARTITION BY B.MEMBER_KEY ORDER BY B.CLINICAL_LABEL) AS RNK
		FROM
		(
			SELECT M.MEMBER_KEY,
			MA.CLINICAL_LABEL,
			SUM(M.MM_UNITS) AS MMC
			FROM FACT_MEMBER_MONTH M
			LEFT JOIN DIM_MARA MA
			ON M.MARA_PRO_CONDITION_KEY = MA.MARACLASS_KEY
			WHERE M.MEMBER_KEY < 100000
			GROUP BY M.MEMBER_KEY, MA.CLINICAL_LABEL
		) B
	
	) MARA
	ON M.MEMBER_KEY = MARA.MEMBER_KEY
	
	LEFT JOIN DIM_MARA MARA_DIM
	ON MARA.CLINICAL_LABEL = MARA_DIM.CLINICAL_LABEL

	WHERE MARA.RNK = 1
	
