
	
	SELECT C.MEMBER_KEY,
	C.AMT_PAID,
	C.AMT_ALLOWED,
	C.QTY_ED_ADMITS,
	C.QTY_DAYS,
	CASE WHEN S.ADMITS = 0 THEN 0 ELSE S.QTY_DAYS/S.ADMITS END	AS AVG_LOS,
	C.ADMITS,
	M.CUR_PROS_RISK_SCORE,
	M.CUR_PRO_RX,
	M.CUR_PRO_IP,
	M.CUR_PRO_OP,
	M.CUR_PRO_PHYSICIAN,
	M.PREV_PROS_RISK_SCORE,
	M.PREV_PRO_RX,
	M.PREV_PRO_OP,
	M.PREV_PRO_IP,
	M.PREV_PRO_PHYSICIAN
	FROM 
	(SELECT
	S.MEMBER_KEY,
	SUM(S.AMT_PAID) AS AMT_PAID,
	SUM(S.AMT_ALLOWED) AS AMT_ALLOWED,
	SUM(COALESCE(S.QTY_ER_ADMITS, 0)) AS QTY_ED_ADMITS,
	SUM(CASE WHEN S.MR_LINE_DESC1 = 'HIP' THEN S.MI_CASES ELSE 0 END) AS ADMITS,
	SUM(CASE WHEN H.HCG_SETTING = 'HIP' THEN S.MI_UTILS ELSE 0 END) AS QTY_DAYS
	FROM FACT_SERVICES s 
	LEFT JOIN DIM_HCG H
		ON S.MR_LINE_CASE_KEY = H.MR_LINE_KEY
	GROUP BY S.MEMBER_KEY) C

	JOIN

	(SELECT MM_A.MEMBER_KEY,
	SUM(MMC. MM) AS MM_COUNT,
	SUM(MM_A.PRO_RX + MM_A.PRO_IP + MM_A.PRO_OP + MM_A.PRO_PHYSICIAN) AS CUR_PROS_RISK_SCORE,
	SUM(MM_A.PRO_RX) AS CUR_PRO_RX,
	SUM(MM_A.PRO_IP) AS CUR_PRO_IP,
	SUM(MM_A.PRO_OP) AS CUR_PRO_OP,
	SUM(MM_A.PRO_PHYSICIAN) AS CUR_PRO_PHYSICIAN,
	SUM(MM_B.PRO_RX + MM_B.PRO_IP + MM_B.PRO_OP + MM_B.PRO_PHYSICIAN) AS PREV_PROS_RISK_SCORE,
	SUM(MM_B.PRO_RX) AS PREV_PRO_RX,
	SUM(MM_B.PRO_IP) AS PREV_PRO_IP,
	SUM(MM_B.PRO_OP) AS PREV_PRO_OP,
	SUM(MM_B.PRO_PHYSICIAN) AS PREV_PRO_PHYSICIAN
	FROM FACT_MEMBER_MONTH MM_A
	LEFT JOIN FACT_MEMBER_MONTH MM_B
	ON MM_A.MEMBER_KEY = MM_B.MEMBER_KEY
	JOIN
		(SELECT 
		MM.MEMBER_KEY,
		SUM(MM.MM_UNITS) AS MM
		FROM FACT_MEMBER_MONTH MM
		GROUP BY MM.MEMBER_KEY) MMC
	ON MM_A.MEMBER_KEY = MMC.MEMBER_KEY
	WHERE MM_A.DATE_KEY = 20160101
	AND MM_B.DATE_KEY = 20150101
	GROUP BY MM_A.MEMBER_KEY) M

	ON C.MEMBER_KEY = M.MEMBER_KEY


