
--Query for claims datasource 

Select
m.MEMBER_NAME,
S.SERVICES_KEY,
S.MEMBER_KEY,
CAST(REPLACE(S.FROM_DATE, '-', '') AS VARCHAR(15)) AS FROM_DATE,
S.CLAIM_ID_KEY, 
cs.UD01_LBL,
cs.UD02_LBL,
cs.UD03_LBL,
cs.UD04_LBL,
cs.UD05_LBL,
cs.UD06_LBL,
cs.UD07_LBL,
cs.UD08_LBL,
cs.UD09_L,
cs.UD10_LBL,
s.MR_LINE_DESC1,
CAST(s.ADM_DATE_KEY AS VARCHAR(15)) AS ADM_DATE,
CAST(s.DIS_DATE_KEY AS VARCHAR(15)) AS DIS_DATE,
s.AMT_PAID,
s.AMT_ALLOWED,
d.ICD_DIAG_CODE_AND_DESC,
p.PROV_ID,
COALESCE(pos.POS_LABEL, 'N/A') AS POS_LABEL,
COALESCE(s.QTY_ER_ADMITS, 0) AS QTY_ER_ADMITS,
CASE WHEN HCGED.MR_LINE_KEY IS NOT NULL THEN ADM_FAC.PROV_NAME ELSE 'N/A' END AS ED_FACILITY,
CASE WHEN S.MR_LINE_DESC1 = 'HIP' THEN S.MI_CASES ELSE 0 END AS ADMITS,
DRG.DRG_LBL AS ADM_DRG,
CASE WHEN ADM_FAC.PROV_KEY IS NULL THEN 'N/A' ELSE COALESCE(NULLIF(ADM_FAC.PROV_NAME,''),'N/A') END AS ADMIT_FACILITY,
CASE WHEN HCGPCP.MR_LINE_KEY IS NOT NULL THEN P.PROV_NAME ELSE 'N/A' END AS PCP_NAME,
CASE WHEN HCGPCP.MR_LINE_KEY IS NOT NULL THEN COALESCE(P.PROV_SPEC_DESC, 'N/A') ELSE 'N/A' END AS PCP_SPECIALTY,
CASE WHEN HCGRX.MR_LINE_KEY IS NOT NULL THEN CAST(RX.RX_NDC_PROD_NAME AS VARCHAR(100)) ELSE 'N/A' END AS DRUG_NAME,
CASE WHEN HCGRX.MR_LINE_KEY IS NOT NULL THEN RX.BRAND_STATUS ELSE 'N/A' END AS DRUG_STATUS,
CASE WHEN HCGRX.MR_LINE_KEY IS NOT NULL THEN CAST(RX.GPI AS VARCHAR(25)) ELSE 'N/A' END AS DRUG_GPI,
CASE WHEN HCGRX.MR_LINE_KEY IS NOT NULL THEN  COALESCE(P.PROV_NAME, 'N/A') ELSE 'N/A' END AS DRUG_PROVIDER,
COALESCE(S.RX_DAYS_SUPPLY, 0) AS DRUG_DAYS_SUPPLY
from fact_Services s 
left join dbo.DIM_CLIENT_SPECIFIC cs
on CS.UDD_KEY = S.UDD_KEY
left join DIM_PROVIDER p
on s.ATT_PROV_KEY = p.PROV_KEY
LEFT JOIN DIM_PROVIDER ADM_FAC
on S.BILL_PROV_KEY = ADM_FAC.PROV_KEY
LEFT JOIN DIM_DRG DRG
on S.DRG_KEY = DRG.DRG_KEY
LEFT JOIN DIM_HCG HCGED
ON S.MR_LINE_CASE_KEY = HCGED.MR_LINE_KEY
   AND HCGED.HCG_LINE_LABEL = 'O11 - Emergency Room'
LEFT JOIN DIM_HCG HCGPCP
ON S.MR_LINE_CASE_KEY = HCGPCP.MR_LINE_KEY
	AND HCGPCP.HCG_LINE_LABEL = 'P32c - PROF Office/Home Visits - PCP'
left join DIM_DIAGNOSIS_ICD d
on S.ICD_DIAG_01_KEY = d.ICD_DIAG_KEY
LEFT JOIN DIM_HCG HCGRX
ON S.MR_LINE_CASE_KEY = HCGRX.MR_LINE_KEY
    AND HCGRX.HCG_SETTING = 'RX'
LEFT JOIN DIM_RX RX
ON S.RX_NDC_KEY = RX.RX_NDC_KEY
left join DIM_POS pos 
on pos.pos_key = s.pos_key
LEFT JOIN DIM_MEMBER m
on s.MEMBER_KEY = m.MEMBER_KEY
where s.member_key = 133203
AND ADM_FAC.PROV_NAME NOT LIKE '%Penlop Care Hospital%'

-- Query for enrollment datasource 

Select DISTINCT 
m.MEMBER_NAME,
mi.age,
mi.gender,
CAST(MM.DATE_KEY AS VARCHAR(15)) AS FROM_DATE,
0 AS CLAIM_ID_KEY, 
cs.UD01_LBL AS UD01_LBL,
cs.UD02_LBL AS UD02_LBL,
cs.UD03_LBL AS UD03_LBL,
cs.UD04_LBL AS UD04_LBL,
cs.UD05_LBL AS UD05_LBL,
cs.UD06_LBL AS UD06_LBL,
cs.UD07_LBL AS UD07_LBL,
cs.UD08_LBL AS UD08_LBL,
cs.UD09_L AS UD09_LBL,
cs.UD10_LBL AS UD10_LBL,
GRP.GROUP_NAME,
mm.MM_UNITS,
COALESCE(mm.PRO_RX, 0) AS PRO_RX,
COALESCE(mm.PRO_IP, 0) AS PRO_IP,
COALESCE(mm.PRO_OP, 0) AS PRO_OP,
COALESCE(mm.PRO_PHYSICIAN, 0) AS PRO_PHYSICIAN,
COALESCE(mm.AS_TOTAL, 0) AS AS_TOTAL
from FACT_MEMBER_MONTH mm
LEFT JOIN DIM_CLIENT_SPECIFIC cs
on  mm.UDD_KEY = CS.UDD_KEY
LEFT JOIN DIM_MEMBER m
on mm.MEMBER_KEY = m.MEMBER_KEY
LEFT JOIN DIM_MEMBER_INFO mi
on MM.MEMBER_INFO_KEY = mi.MEMBER_INFO_KEY
LEFT JOIN DIM_GROUP GRP
ON MM.GRP_KEY = GRP.GRP_KEY
where MM.MEMBER_KEY = 133203
AND MM.MM_UNITS > 0